mpKR = {
   	m0: 'MopiMopi Overlay',
    m1: '请开始你的表演。',
    m7: '历史记录<i class="material-icons left" style="color: rgba(255,255,255,0.5)">history</i>',
    m3: '隐藏角色名<i class="material-icons left" style="color: rgba(255,255,255,0.5)">visibility_off</i>',
    m2: '查看治疗数据<i class="material-icons left" style="color: rgba(255,255,255,0.5)">local_hospital</i>',
    m6: '全屏模式<i class="material-icons left" style="color: rgba(255,255,255,0.5)">fullscreen</i>',
    m5: '设置<i class="material-icons left" style="color: rgba(255,255,255,0.5)">settings</i>',
    m10: '设置',
    m20: '定制',
    m11: '基础ACT内容',
    m30: '您阔以通过选择多个项目来创建专属的ACT。',
    m12: '治疗ACT内容',
    m31: '当你选中了‘查看治疗数据’时可以创建专属的治疗ACT',
    m21: '数据处理',
    m80: '合并召唤兽数据',
    m81: '合并召唤兽数据.<br><font class="rdColor">= </font>召唤师、机工师、学者',
    m170: '显示召唤兽图标',
    m171: '显示召唤兽伤害和治疗.<br><font class="rdColor">= </font>合并召唤兽数据 \'ON\'',
    m82: '数字类型',
    m83: '<font class="rdColor">OFF </font>整数<font class="rdColor">　　ON </font>小数点',
    m84: '千位分隔符',
    m85: '<font class="rdColor">OFF </font>1234<font class="rdColor">　　ON </font>1,234',
    m207: '名字类型',
    m208: '全名',
    m209: '姓氏缩写',
    m210: '全字母缩写',
    m211: '姓氏首字母缩写',
    m212: '团队(DPS排序)',
    m213: '<font class="rdColor">OFF </font>YOU<font class="rdColor">　　ON </font>1. YOU',
    m225: '全局服务器',
     m226: '设置overlay数字或字符的数据类型.',
    m227: '应用欧洲数字符号',
    m228: '将数字数据的句点（。）和逗号（，）互换',
    m229: '缩写操作 (MaxHit/Heal)',
    m230: '<font class="rdColor">OFF </font>Midare Setsugekka<font class="rdColor">　　ON </font>Midare',
    m233: '自动隐藏数据表',
    m234: '当encounter结束时，自动隐藏数据表等待时间。',
    m235: '其他设置',
    m236: '更改其他设置的属性。<br><font class="rdColor">= </font>overlay和数据表等',
    m237: 'Overlay缩放箭头',
    m238: '<font class="rdColor">OFF </font>隐藏<font class="rdColor">　　ON </font>显示',
    m239: '数据表',
    m240: '菜单工具提示',
    m241: 'Toast消息',
    m242: '<span class="PrimaryText">延迟时间</span><br><span class="SecondaryText"><font class="rdColor">= </font>단위 \'分\'</span>',
    m243: '备份',
    m244: '你可以备份或者还原UI设置.',
    m245: '<span>上次备份的时间<font id="backupDate" class="rdColor"></font></span>',
    m246: '恢复',  
    m247: '将UI设置恢复到以前的数据。',
    m248: '我的数据',
    m249: '导出设置',    
    m250: '导入设置',  
    m251: '复制下面的字符串（CTRL+C）',  
    m252: '粘贴在要应用的值（Ctrl + V）下，然后按Enter键。',
    m253: '备份和恢复',
    m254: '没有数据，请点击备份保存数据。',
    m255: '你特喵确定要恢复？',
    m256: 'Index',
    m257: '数据输出顺序',
    m258: '更改数据表中列的顺序.',
    m259: '我的角色名',
    m260: '<font class="rdColor">OFF </font>YOU<font class="rdColor">　　ON </font>例如 波波鸟 ',
    m261: '技能的名字缩写管理',
    m262: '您可以注册或删除操作的技能缩写。',
    m263: '<br>1. 夏基儿翻译',
    m264: '注册',
    m265: '技能的名字（重要！间距）',
    m266: '缩写',
    m267: '列表',
    m268: '提交',
    m269: '对齐格式',
    m270: '<font class="rdColor">OFF </font>가운데<font class="rdColor">　　ON </font>离',
    m22: '显示',
    m13: '语言',
    m14: '字体',
    m184: '更改字体属性.<br><font class="rdColor">= </font>字体, 大小, 颜色, 风格',
    m19: '导航栏',
    m86: '设计导航栏以适应个人口味。',
    m23: '图形',
    m87: '更改图形的属性。.<br><font class="rdColor">= </font>颜色,效果, 透明度',
    m16: '单元格宽度',
    m91: '按组调整单元格的宽度。',
    m24: '版本和开发者信息',
    m150: '版本',
    m152: '联系我们',
    m153: 'ffxivHAERU@gmail.com',
    m200: 'About the Developer',
    m201: 'Korea [Moogle] <font class="rdColor">= </font>Haeru, Laiglinne, Ikaruga<br>Korea [Carbuncle] <font class="rdColor">= </font>CoolnyamCoolnyam',
    m25: '重置',
	 m26: '管理工具',
    m162: '您可以使用此选项将所有设置的值恢复为默认值。',
    m163: '对设置的任何更改将恢复为默认值，您的个人数据将被删除。 你想继续进行初始化吗？',
    m167: '刷新',
    m168: 'overlay操作异常时使用此选项。<br>历史记录将被删除。',
    m90: '更改您的计算机上安装的字体。<Br><font class="rdColor">= </font>Only PC',
    m102: '在设置之前阅读',
    m103: '当你直接输入,<br>ACT > Plugins > ACTWebSocket >Click "Open Manager" > Tab "Preferences" > UNCHEKED "No Focus"',
    m101: '<br>1.只能输入字体名称。 （除了字体样式）<br> 2。 如果字体文件损坏或字体名称输入错误，则默认应用该字体。 这个功能在移动环境下是不支持的.',
    m96: '时间 (00:00)',
     m97: '通常',
    m98: '中文',
    m99: '日文',
    m104: '英文',
    m105: '德语',
    m176: '大小',
    m177: '<span class="PrimaryText">大小<br><span class="SecondaryText"><font class="rdColor">= </font>8px ~ 32px</span></span>',
    m129: '颜色',
    m147: '<span class="PrimaryText">用户<br><span class="SecondaryText"><font class="rdColor">= </font>YOU</span></span>',
    m148: '<span class="PrimaryText">其他<br><span class="SecondaryText"><font class="rdColor">= </font>파티원</span></span>',
    m186: '强调角色的文字：YOU',
    m187: '在数据表中将粗体格式应用于用户的文本。',
    m188: '强调角色的文字：其他',
    m189: '在数据表中将粗体格式应用于其他人的文本。',
    m183: '<span class="PrimaryText">高度</span><br><span class="SecondaryText"><font class="rdColor">= </font>2px调整</span>',
    m100: '预览',
    m190: '<span class="PrimaryText">背景颜色 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>导航栏 *</span>',
    m172: '<span class="PrimaryText">强调色</span><br><span class="SecondaryText"><font class="rdColor">= </font>时间 (00:00), 图标</span>',
    m199: '<span class="PrimaryText">边框颜色</span><br><span class="SecondaryText"><font class="rdColor">= </font>导航栏 *</span>',
    m191: '<span class="PrimaryText">文本颜色 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>导航栏 *<br><font class="rdColor">= </font>目标名称</span>',
    m192: '<span class="PrimaryText">文本颜色 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>导航栏 *<br><font class="rdColor">= </font>团秒伤, 团秒疗</span>',
    m219: '<span class="PrimaryText">背景颜色 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>表头 *</span>',
    m222: '<span class="PrimaryText">文本颜色 3</span><br><span class="SecondaryText"><font class="rdColor">= </font>表头 *</span>',
    m194: '圆角',
    m195: '将导航栏的左上角和右上角四舍五入。',
    m197: '画边界',
    m198: '导航栏周围有1px边框.',
    m181: '不透明度',
    m193: '导航栏不透明度',
    m221: '标题不透明度',
    m17: '图表颜色',
    m119: '改变图形的颜色。',
    m88: '画分区线',
    m89: '在图形之间绘制分界线。',
    m120: '用渐变填充图形',
    m121: '对图形应用渐变效果。',
     m122: '使用动画过渡效果',
    m123: '当DPS值或HPS值改变时，平滑地显示图形。',
    m15: '背景不透明度',
    m18: '图不透明度',
    m204: '效果',
    m217: '激活团队模式',
    m218: '如果战斗员人数超过九人，则数据表显示简短.',
    m109: '窄单元格',
    m111: '窄单元格 1',
    m112: '变化小的单元格<br><font class="rdColor">= </font>Job, D%, Death等',
    m113: '窄单元格 2',
    m114: 'DPS, HPS 单元格',
    m110: '宽单元格',
    m115: '宽单元格 1',
    m116: '变化大的单元格<br><font class="rdColor">= </font>Damage, Healed 等',
    m117: '宽单元格 2',
    m118: 'MaxHit, MaxHeal 等',
    m154: 'MopiMopi Overlay 皮肤',
    m155: 'Korea [Moogle] Haeru<br>GitHub <font class="rdColor">= </font>HAERUHAERU',
    m160: 'ACT Core Library : Chamsucript (js/core.js)',
    m161: 'Korea [Moogle] Laiglinne<Br>Elemental [Alexander] Lulala Lula<br>GitHub <font class="rdColor">= </font>laiglinne-ff',
    m156: 'Translation (中文)',
    m157: 'Korea [Moogle] Ikaruga',
    m271: '번역 (독일어)',
    m272: 'Chaos [Phoenix] Shunittseru Tohka',
    m158: 'ACT WebSocket Overlay Plugin',
    m159: 'Korea [Carbuncle] CoolnyamCoolnyam<br>GitHub <font class="rdColor">= </font>ZCube',
    m205: '应用用户颜色',
    m206: '将用户的图标应用于YOU选择的颜色，而不考虑职业或特职。',
    m124: '坦克',
    m9: '颜色代码',
    m130: '<span class="PrimaryText">骑士</span><br><span class="SecondaryText"><font class="rdColor">= </font>剑术师</span>',
    m131: '<span class="PrimaryText">战士</span><br><span class="SecondaryText"><font class="rdColor">= </font>斧术师</span>',
    m132: '<span class="PrimaryText">暗黑骑士</span>',
    m125: '治疗',
    m133: '<span class="PrimaryText">白魔法师</span><br><span class="SecondaryText"><font class="rdColor">= </font>幻术师</span>',
    m134: '<span class="PrimaryText">学者</span>',
    m135: '<span class="PrimaryText">占星术士</span>',
    m165: '<span class="PrimaryText">伤害护盾</span><br><span class="SecondaryText"><font class="rdColor">= </font>治疗ACT *</span>',
    m166: '<span class="PrimaryText">过量治疗</span><br><span class="SecondaryText"><font class="rdColor">= </font>治疗ACT *</span>',
    m126: 'DPS',
    m136: '<span class="PrimaryText">武僧</span><br><span class="SecondaryText"><font class="rdColor">= </font>拳术师</span>',
    m137: '<span class="PrimaryText">龙骑士</span><br><span class="SecondaryText"><font class="rdColor">= </font>枪术师</span>',
    m138: '<span class="PrimaryText">忍者</span><br><span class="SecondaryText"><font class="rdColor">= </font>双剑士</span>',
    m231: '<span class="PrimaryText">武士</span>',
    m139: '<span class="PrimaryText">黑魔法师</span><br><span class="SecondaryText"><font class="rdColor">= </font>咒术师</span>',
    m140: '<span class="PrimaryText">召唤师</span><br><span class="SecondaryText"><font class="rdColor">= </font>秘术师</span>',
    m232: '<span class="PrimaryText">赤魔法师</span>',
    m141: '<span class="PrimaryText">吟游诗人</span><br><span class="SecondaryText"><font class="rdColor">= </font>弓术士</span>',
    m142: '<span class="PrimaryText">机工士</span>',
    m127: '采集 / 生产',
    m143: '<span class="PrimaryText">采集</span><br><span class="SecondaryText"><font class="rdColor">= </font>3种</span>',
    m144: '<span class="PrimaryText">生产</span><br><span class="SecondaryText"><font class="rdColor">= </font>8种</span>',
    m128: '其他',
    m145: '<span class="PrimaryText">极限技</span><br><span class="SecondaryText"><font class="rdColor">= </font>Limit Break</span>',
    m169: '<span class="PrimaryText">宠物数据</span><br><span class="SecondaryText"><font class="rdColor">= </font>50%透明度<br><font class="rdColor">= </font>在用户图表上方 *</span>',
    m146: '<span class="PrimaryText">陆行鸟</span><br><span class="SecondaryText"><font class="rdColor">= </font>伙伴</span>',
    m220: '<span class="PrimaryText">背景颜色</span><br><span class="SecondaryText"><font class="rdColor">= </font>背景图标 *</span>',
    m223: '<span class="PrimaryText">分区线颜色</span><br><span class="SecondaryText"><font class="rdColor">= </font>画分区线 \'ON\'</span>',
    m224: '分区线不透明度',
    m32: '玩家介绍',
    m33: '战斗项',
    m34: '承伤项',
    m35: '治疗项',
    m36: '其他',
    m37: '战斗员的等级和名字',
    m214: '战斗人员的名字',
    m38: '玩家的职业或者特职业图标',
    m39: '战斗的持续时间<br><font class="rdColor">= </font>在自己开始攻击的时候',
    m40: '秒伤<br><font class="rdColor">= </font>P.Time 時点',
    m41: '战斗日志收集时间<br><font class="rdColor">= </font>队员首次受到攻击',
    m42: '秒伤<br><font class="rdColor">= </font>Time 時点，官方',
    m43: '最近10秒平均DPS',
    m44: '最近30秒平均DPS',
    m45: '最近60秒平均DPS',
    m46: '最近180秒平均DPS',
    m47: '此值表示队友在这次战斗中所造成的所有伤害百分比。',
    m48: '伤害总量',
    m49: '命中率 (%)',
    m50: '攻击次数<br><font class="rdColor">= </font>包括自动攻击，DOT，技能',
    m51: '攻击命中的次数',
    m52: '攻击未命中次数',
    m53: '攻击失败的次数<br><font class="rdColor">= </font>敌人抗性发动，反弹，阻碍，回避 等',
    m54: '攻击暴击次数',
    m55: '攻击暴击率 (%)',
    m56: '最大伤害的技能',
    m57: '受到伤害量',
    m58: '受到治疗量',
    m59: '招架率 (%)',
    m60: '盾牌格挡 (%)',
    m61: '秒治疗量<br><font class="rdColor">= </font>Time Time 時点、官方',
    m62: '战斗者的治疗总数除以战斗的持续时间 (%)',
    m63: '总治疗量',
    m64: '有效的治疗量',
    m65: '被治疗者抵消的伤害数量。<br><font class="rdColor">= </font>石肤，鼓舞，吉星等',
    m66: '过量治疗量',
    m67: '过量治疗率 (%)',
    m68: '治疗咏唱次数<br><font class="rdColor">= </font>包括HOT，技能，能力',
    m69: '恢复技能暴击次数',
    m70: '恢复技能暴击率 (%)',
    m71: '最大治疗量技能',
    m72: '驱散净化次数<br><font class="rdColor">= </font>如 康复',
    m73: '技能的HP回复量<br><font class="rdColor">= </font>如 慈悲杀',
    m74: '技能的MP回复量<br><font class="rdColor">= </font>如 以太超流',
    m75: '死亡回数',
    m76: '直击次数<br><font class="rdColor">= </font>4.0 新增',
    m77: '直击率(%)<br><font class="rdColor">= </font>4.0 新增',
    m78: '直击暴击次数<br><font class="rdColor">= </font>4.0 新增',
    m79: '直击暴击率(%)<br><font class="rdColor">= </font>4.0 新增',
};
mpJP = {
    m0: 'モピモピオーバーレイ',
    m1: '戦闘を始めてください。',
    m7: '履歴<i class="material-icons left" style="color: rgba(255,255,255,0.5)">history</i>',
    m3: 'キャラの名前を隠す<i class="material-icons left" style="color: rgba(255,255,255,0.5)">visibility_off</i>',
    m2: 'ヒーラーのACTを見る<i class="material-icons left" style="color: rgba(255,255,255,0.5)">local_hospital</i>',
    m6: 'フルスクリーンモード<i class="material-icons left" style="color: rgba(255,255,255,0.5)">fullscreen</i>',
    m5: '設定<i class="material-icons left" style="color: rgba(255,255,255,0.5)">settings</i>',
    m10: '設定',
    m20: 'カスタマイズ',
    m11: 'ACTの基本セッティング',
    m30: '色んな組み合わせで自分だけのACTを作成できます。',
    m12: 'ヒーラーのACT設定',
    m31: '\'ヒーラーのACTを見る\'にチェークを入れると、ヒーラーACTに出力する項目を編集できるようになります。',
    m21: 'データ処理',
    m80: 'ペットのデータを合算する',
    m81: 'オーバーレイ内にプレイヤーとペットのデータを合算します。<br><font class="rdColor">= </font>召喚士、機工士、学者',
    m170: 'プレイヤーのグラフにペットのグラフを表示する',
    m171: 'プレイヤーのグラフにペットのダーメジもしくはヒール量の割合を表紙する<br><font class="rdColor">= </font>ペットのデータを合算する \'ON\'',
    m82: '数字データタイプ',
    m83: '<font class="rdColor">OFF </font>整數<font class="rdColor">　　ON </font>小數',
    m84: '3桁ごとに区切りを表示する',
    m85: '<font class="rdColor">OFF </font>1234<font class="rdColor">　　ON </font>1,234',
    m207: '名前の表示タイプ',
    m208: 'フルネーム',
    m209: '姓のみイニシャル',
    m210: '名のみイニシャル',
    m211: '姓名ともにイニシャル',
    m212: 'ランク (DPS 基準)',
    m213: '<font class="rdColor">OFF </font>YOU<font class="rdColor">　　ON </font>1. YOU',
    m225: 'グローバルサーバ',
    m226: 'Sets the data type of the number or character in overlay.',
    m227: 'Apply European Numeric Notation',
    m228: 'Change the period(.) and commas(,) of the numeric data to each other.',
    m229: 'Abbreviate Action\'s Name',
    m230: '<font class="rdColor">OFF </font>Midare Setsugekka<font class="rdColor">　　ON </font>Midare',
    m233: 'Auto-hide the Data Table',
    m234: 'When the encounter is end, hides the data table after latency time automatically.',
    m235: 'その他の設定',
    m236: 'その他の設定を変更します。<br><font class="rdColor">= </font>オーバーレイ、データテーブルなど',
    m237: 'Overaly Resizing Arrow',
    m238: '<font class="rdColor">OFF </font>Hide<font class="rdColor">　　ON </font>Show',
    m239: 'データテーブル',
    m240: 'Menu Tooltips',
    m241: 'Toast Meassage',
    m242: '<span class="PrimaryText">Latency Time</span><br><span class="SecondaryText"><font class="rdColor">= </font>Unit \'Minute\'</span>',
    m243: 'Backup',
    m244: 'You can backup or restore the UI Settings. Or you share or apply it with other users.',
    m245: '<span>Date and time of last backup<font id="backupDate" class="rdColor"></font></span>',
    m246: 'Restore',  
    m247: 'Restore UI settings to previous data.',
    m248: 'My data',
    m249: 'Export the Customizing',    
    m250: 'Import the Customizing',  
    m251: 'Copy under the values (Ctrl+C). NOT contain some values.',  
    m252: 'Paste under the values to apply (Ctrl+V), and then Press the Enter key.',
    m253: 'Backup and Restore',
    m254: 'No data. Please click Backup to save the data.',
    m255: 'Do you really want to restore it?',
    m256: 'Index',    
    m257: 'Data Output Order',
    m258: 'Change the order of the columns in data table.',
    m259: 'My Character Name',
    m260: '<font class="rdColor">OFF </font>YOU<font class="rdColor">　　ON </font>ex) Lulala Lula',    
    m261: 'Action\'s name Abbreviations Management',
    m262: 'You can register or delete action\'s name abbreviations.',
    m263: '',
    m264: 'Register',
    m265: 'Action\'s name (Important! Spacing)',
    m266: 'Abbreviation',
    m267: 'List',
    m268: 'Submit',
    m269: 'Format Align',
    m270: '<font class="rdColor">OFF </font>Center<font class="rdColor">　　ON </font>Left',
    m22: 'ディスプレー',
    m13: '言語',
    m14: 'フォント',
    m184: 'フォントの属性を変更します。<br><font class="rdColor">= </font>フォント、サイズ、色、スタイル',
    m19: '上段バー',
    m86: '上段バーを好みに合わせて変更します。',
    m23: 'グラフ',
    m87: 'グラフの属性を変更します。<br><font class="rdColor">= </font>色、効果、不透明度',
    m16: 'セルの幅',
    m91: 'セルの幅をグループごとに調整します。',
    m24: 'バージョンと開発者情報',
    m150: 'バージョン情報',
    m152: '問い合わせ',
    m153: 'ffxivHAERU@gmail.com',
    m200: '開発者紹介',
    m201: 'Thanks to :)',
    m25: '初期化',
    m26: '管理ツール',
    m162: '全ての設定を基本値に戻す。',
    m163: '設定のよるすべての変更を基本値に戻し、個人データを削除します。初期化を進行しますか？',
    m167: 'リーロド',
    m168: 'オーバーレイがうまく動作しない時に使用してください。<br>前に作成された履歴を除去します。',
    m90: 'PCに設置されているフォントでテキストを変更します。<br><font class="rdColor">= </font>PCのみ可能',
    m102: '設定する前の注意事項',
    m103: 'キーボード入力の場合は,<br>ACT > Plugins > ACTWebSocket > 오버레이 관리자 > 설정 "키 입력 무시"のチェークを解除してください',
    m101: '1. フォントの名前だけ入力してください。(フォントスタイル除外)<br>2. フォントのファイルが損傷されている、もしくは名前が間違っている場合は基本フォントが適用されます。<br>3. 携帯環境では該当オプションは使用できません。',
    m96: '時間 (00:00)',
    m97: '一般',
    m98: '韓國語',
    m99: '日本語',
    m104: '英語',
    m105: '獨逸語',
    m176: 'サイズ',
    m177: '<span class="PrimaryText">フォントサイズ<br><span class="SecondaryText"><font class="rdColor">= </font>8px ~ 32px</span></span>',
    m129: 'テクストの色',
    m147: '<span class="PrimaryText">自分のキャラクター<br><span class="SecondaryText"><font class="rdColor">= </font>YOU</span></span>',
    m148: '<span class="PrimaryText">他のキャラクター<br><span class="SecondaryText"><font class="rdColor">= </font>パーティーメンバー</span></span>',
    m186: '自キャラのテキストを強調する',
    m187: 'データテーブルで表示される自分のキャラクターのテキストを太字にする。',
    m188: '他キャラのテキストを強調する',
    m189: 'データテーブルで表示される他のキャラクターのテキストを太字にする。',
    m183: '<span class="PrimaryText">高さ</span><br><span class="SecondaryText"><font class="rdColor">= </font>2ずつ調整</span>',
    m100: 'プレビュー',
    m190: '<span class="PrimaryText">背景色 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>メーンの上段バー</span>',
    m172: '<span class="PrimaryText">強調色</span><br><span class="SecondaryText"><font class="rdColor">= </font>時間 (00:00), アイコン</span>',
    m199: '<span class="PrimaryText">枠線の色</span><br><span class="SecondaryText"><font class="rdColor">= </font>メーンの上段バー</span>',
    m191: '<span class="PrimaryText">テキストの色 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>ターゲットの名前</span>',
    m192: '<span class="PrimaryText">テキストの色 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>RDPS, RHPS</span>',
    m219: '<span class="PrimaryText">背景色 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>テーブルヘッダ</span>',
    m222: '<span class="PrimaryText">テキストの色 3</span><br><span class="SecondaryText"><font class="rdColor">= </font>テーブルヘッダ</span>',
    m221: 'ヘッダ不透明度',
    m194: '角を丸くする',
    m195: 'メイン上段バーの右と左の上段角に角丸を適用します。',
    m197: '枠線描き',
    m198: 'メイン上段バーに1pxの線を引きます。',
    m181: '不透明度',
    m193: '上段バーの不透明度',
    m17: 'グラフの色',
    m119: 'グラフの色を変更します。',
    m88: '区分線を表示する',
    m89: 'グラフの間に区切り線を表示します。',
    m120: 'グラデーション効果を使用する',
    m121: 'グラフにグラデーション効果を適用します。',
    m122: 'アニメーション変換効果を使用する',
    m123: 'DPS及びHPS変動時グラフをより滑らかに表示します。',
    m15: '背景の不透明度',
    m18: 'グラフ不透明度',
    m204: '効果',
    m217: 'Active the Raid Mode',
    m218: 'If the number of combatants exceeds nine people, the data table displays briefly.',
    m109: '狭いセル',
    m111: '狭いセル 1',
    m112: '変動値が低いセル<br><font class="rdColor">= </font>Job, D%, Deathなど',
    m113: '狭いセル 2',
    m114: 'DPS, HPS',
    m110: '広いセル',
    m115: '広いセル 1',
    m116: '変動値が高いセル<br><font class="rdColor">= </font>Damage, Healedなど',
    m117: '広いセル 2',
    m118: 'MaxHit, MaxHeal',
    m154: 'モピモピオーバーレイスキン',
    m155: 'Korea [Moogle] Haeru<br>GitHub <font class="rdColor">= </font>HAERUHAERU',
    m160: 'ACT コア ライブラリ : Chamsucript (js/core.js)',
    m161: 'Korea [Moogle] Laiglinne<Br>Elemental [Alexander] Lulala Lula<br>GitHub <font class="rdColor">= </font>laiglinne-ff',
    m156: '翻訳 (日本語)',
    m157: 'Korea [Moogle] Ikaruga',
    m271: '翻訳 (獨逸語)',
    m272: 'Chaos [Phoenix] Shunittseru Tohka',
    m158: 'ACT ウェブソケット オーバーレイ フラグイン',
    m159: 'Korea [Carbuncle] CoolnyamCoolnyam<br>GitHub <font class="rdColor">= </font>ZCube',
    m205: 'Applies a User Color',
    m206: 'Applies the user\'s graph in a color you choose regardless of class or job.',
    m9: '色コード',
    m124: 'タンク',
    m130: '<span class="PrimaryText">ナイト</span><br><span class="SecondaryText"><font class="rdColor">= </font>剣術士</span>',
    m131: '<span class="PrimaryText">戦士</span><br><span class="SecondaryText"><font class="rdColor">= </font>斧術士</span>',
    m132: '<span class="PrimaryText">暗黒騎士</span>',
    m125: 'ヒーラー',
    m133: '<span class="PrimaryText">白魔道士</span><br><span class="SecondaryText"><font class="rdColor">= </font>幻術士</span>',
    m134: '<span class="PrimaryText">学者</span>',
    m135: '<span class="PrimaryText">占星術師</span>',
    m165: '<span class="PrimaryText">バリアヒール量</span><br><span class="SecondaryText"><font class="rdColor">= </font>ヒーラーACT</span>',
    m166: '<span class="PrimaryText">オーバーヒール量 </span><br><span class="SecondaryText"><font class="rdColor">= </font>ヒーラーACT</span>',
    m126: 'アタッカー',
    m136: '<span class="PrimaryText">モンク</span><br><span class="SecondaryText"><font class="rdColor">= </font>格闘士</span>',
    m137: '<span class="PrimaryText">竜騎士</span><br><span class="SecondaryText"><font class="rdColor">= </font>槍術士</span>',
    m138: '<span class="PrimaryText">忍者</span><br><span class="SecondaryText"><font class="rdColor">= </font>双剣士</span>',
    m231: '<span class="PrimaryText">侍</span>',
    m139: '<span class="PrimaryText">黒魔道士</span><br><span class="SecondaryText"><font class="rdColor">= </font>呪術士</span>',
    m140: '<span class="PrimaryText">召喚士</span><br><span class="SecondaryText"><font class="rdColor">= </font>巴術士</span>',
    m232: '<span class="PrimaryText">赤魔道士</span>',
    m141: '<span class="PrimaryText">吟遊詩人</span><br><span class="SecondaryText"><font class="rdColor">= </font>弓術士</span>',
    m142: '<span class="PrimaryText">機工士</span>',
    m127: '採集 / 製作',
    m143: '<span class="PrimaryText">採集</span><br><span class="SecondaryText"><font class="rdColor">= </font>3種</span>',
    m144: '<span class="PrimaryText">製作</span><br><span class="SecondaryText"><font class="rdColor">= </font>8種</span>',
    m128: 'その他',
    m145: '<span class="PrimaryText">リミットブレイク</span><br><span class="SecondaryText"><font class="rdColor">= </font>Limit Break</span>',
    m169: '<span class="PrimaryText">ペットのデータ</span><br><span class="SecondaryText"><font class="rdColor">= </font>不透明度 50%<br><font class="rdColor">= </font>ユーザーグラフの上</span>',
    m146: '<span class="PrimaryText">チョコボ</span><br><span class="SecondaryText"><font class="rdColor">= </font>バディ</span>',
    m220: '<span class="PrimaryText">背景色</span><br><span class="SecondaryText"><font class="rdColor">= </font>グラフ背景</span>',
    m223: '<span class="PrimaryText">区分線の色</span><br><span class="SecondaryText"><font class="rdColor">= </font>区分線を表示する \'ON\'</span>',
    m224: '区分線の不透明度',
    m32: 'プレイヤー情報',
    m33: '戦闘項目',
    m34: '被害項目',
    m35: '回復項目',
    m36: 'その他',
    m37: '順位とキャラ名',
    m214: 'キャラ名',
    m38: 'クラスもしくはジョブアイコン',
    m39: '戦闘ログ収集時間<br><font class="rdColor">= </font>自らの攻撃した時点',
    m40: '1秒あたりのダメージ<br><font class="rdColor">= </font>P.Time 時点',
    m41: '戦闘ログ収集時間<br><font class="rdColor">= </font>パティー初めて攻撃した時点',
    m42: '1秒あたりのダメージ<br><font class="rdColor">= </font>Time 時点、オフィシャル',
    m43: '最近10秒間の平均DPS',
    m44: '最近30秒間の平均DPS',
    m45: '最近60秒間の平均DPS',
    m46: '最近180秒間の平均DPS',
    m47: '総ダメージ中自分が与えたダメージ量 (%)',
    m48: 'ダメージ量',
    m49: '命中率 (%)',
    m50: '攻撃回数<br><font class="rdColor">= </font>オートアタック、DOT、スキルキャンセル含め',
    m51: '攻撃の命中回数',
    m52: '攻撃のミス回数',
    m53: '攻撃の失敗回数<br><font class="rdColor">= </font>敵の抵抗、反射、ブロック、回避など',
    m54: '攻撃のクリティカル回数',
    m55: '攻撃のクリティカル率 (%)',
    m56: '最大ダメージのスキル',
    m57: '受けた被ダメージ量',
    m58: '貰ったヒール量',
    m59: '受け流し発動率 (%)',
    m60: '盾ブロック発動率 (%)',
    m61: '1秒あたりのヒール量<br><font class="rdColor">= </font>Time 時点、オフィシャル',
    m62: '総ヒール量中自分が回復したヒール量 (%)',
    m63: '総ヒール量',
    m64: '有効総ヒール量',
    m65: 'バリアヒール量<br><font class="rdColor">= </font>鼓舞、ノクターナルセクト',
    m66: 'オーバーヒール量',
    m67: 'オーバーヒール率 (%)',
    m68: 'ヒール回数<br><font class="rdColor">= </font>HOT、スキルキャンセル含む',
    m69: '回復のクリティカル回数',
    m70: '回復のクリティカル率 (%)',
    m71: '最大回復のスキル',
    m72: 'デバフ解除スキルの使用回数<br><font class="rdColor">= </font>エスナ',
    m73: 'スキルのよるHP回復量<br><font class="rdColor">= </font>マーシーストロークなど',
    m74: 'スキルのよるMP回復量<br><font class="rdColor">= </font>エーテルフローなど',
    m75: '死亡回数',
    m76: 'Direct Hits 回数',
    m77: 'Direct Hits 発動率 (%)',
    m78: 'Direct Hits クリティカル回数',
    m79: 'Direct Hits クリティカル率 (%)',
};
mpEN = {
    m0: 'MopiMopi Overlay',
    m1: 'Please start the combat.',
    m7: 'History<i class="material-icons left" style="color: rgba(255,255,255,0.5)">history</i>',
    m3: 'Hide the R. Name<i class="material-icons left" style="color: rgba(255,255,255,0.5)">visibility_off</i>',
    m2: 'View Healer ACT<i class="material-icons left" style="color: rgba(255,255,255,0.5)">local_hospital</i>',
    m6: 'Fullscreen Mode<i class="material-icons left" style="color: rgba(255,255,255,0.5)">fullscreen</i>',
    m5: 'Settings<i class="material-icons left" style="color: rgba(255,255,255,0.5)">settings</i>',
    m10: 'Settings',
    m20: 'Customizing',
    m11: 'Basic ACT Fomatting',
    m30: 'You can create my own ACT by selecting the multiple items.',
    m12: 'Healer ACT Formatting',
    m31: 'You can select the items to output on Healer ACT when \'View Healer ACT\' is checked.',
    m21: 'Data Processing',
    m80: 'Combine Pets with Owner',
    m81: 'Combine the pet\'s data with the owner\'s data within the overlay.<br><font class="rdColor">= </font>SMN, MCH, SCH',
    m170: 'Display Pet\'s Graph on User Graph',
    m171: 'Displays the percentage of pet\'s Damage or Healed on the user graph.<br><font class="rdColor">= </font>Combine Pets with Owner \'Checked\'',
    m82: 'Number Data Type',
    m83: '<font class="rdColor">OFF </font>Integer<font class="rdColor">　　ON </font>Decimal',
    m84: 'Thousand Separators',
    m85: '<font class="rdColor">OFF </font>1234<font class="rdColor">　　ON </font>1,234',
    m207: 'Name Display Type',
    m208: 'Full Name',
    m209: 'Surname Abbreviated',
    m210: 'Forename Abbreviated',
    m211: 'Initials',
    m212: 'Ranking (Sort by DPS)',
    m213: '<font class="rdColor">OFF </font>YOU<font class="rdColor">　　ON </font>1. YOU',
    m225: 'Global Server',
    m226: 'Sets the data type of the number or character in overlay.',
    m227: 'Apply European Numeric Notation',
    m228: 'Change the period(.) and commas(,) of the numeric data to each other.',
    m229: 'Abbreviate Action\'s Name',
    m230: '<font class="rdColor">OFF </font>Midare Setsugekka<font class="rdColor">　　ON </font>Midare',
    m233: 'Auto-hide the Data Table',
    m234: 'When the encounter is end, hides the data table after latency time automatically.',
    m235: 'Other Settings',
    m236: 'Change the properties of other settings.<br><font class="rdColor">= </font>Overlay, Data Table etc.',
    m237: 'Overaly Resizing Arrow',
    m238: '<font class="rdColor">OFF </font>Hide<font class="rdColor">　　ON </font>Show',
    m239: 'Data Table',
    m240: 'Menu Tooltips',
    m241: 'Toast Meassage',
    m242: '<span class="PrimaryText">Latency Time</span><br><span class="SecondaryText"><font class="rdColor">= </font>Unit \'Minute\'</span>',
    m243: 'Backup',
    m244: 'You can backup or restore the UI Settings. Or you share or apply it with other users.',
    m245: '<span>Date and time of last backup<font id="backupDate" class="rdColor"></font></span>',
    m246: 'Restore',  
    m247: 'Restore UI settings to previous data.',
    m248: 'My data',
    m249: 'Export the Customizing',    
    m250: 'Import the Customizing',  
    m251: 'Copy under the values (Ctrl+C). NOT contain some values.',  
    m252: 'Paste under the values to apply (Ctrl+V), and then Press the Enter key.',
    m253: 'Backup and Restore',
    m254: 'No data. Please click Backup to save the data.',
    m255: 'Do you really want to restore it?',
    m256: 'Index',
    m257: 'Data Output Order',
    m258: 'Change the order of the columns in data table.',
    m259: 'My Character Name',
    m260: '<font class="rdColor">OFF </font>YOU<font class="rdColor">　　ON </font>ex) Lulala Lula',
    m261: 'Action\'s name Abbreviations Management',
    m262: 'You can register or delete action\'s name abbreviations.',
    m263: '',
    m264: 'Register',
    m265: 'Action\'s name (Important! Spacing)',
    m266: 'Abbreviation',
    m267: 'List',
    m268: 'Submit',
    m269: 'Format Align',
    m270: '<font class="rdColor">OFF </font>Center<font class="rdColor">　　ON </font>Left',
    m22: 'Display',
    m13: 'Language',
    m14: 'Font',
    m184: 'Change the properties of font.<br><font class="rdColor">= </font>Font, Size, Color, Style',
    m19: 'Navigation Bar',
    m86: 'Designs the navigation bar to suit individual tastes.',
    m23: 'Graph',
    m87: 'Change the properties of graph.<br><font class="rdColor">= </font>Color, Effect, Opacity',
    m16: 'Cell Width',
    m91: 'Adjust the width of cells by groups.',
    m24: 'Version and Developer Info',
    m150: 'Version',
    m152: 'Contact Us',
    m153: 'ffxivHAERU@gmail.com',
    m200: 'About the Developer',
    m201: 'Thanks to :)',
    m25: 'Reset',
    m26: 'Management Tools',
    m162: 'You use this option that restore the values for all settings to the default.',
    m163: 'Any changes to the settings will be restored to their defaults and your personal data will be deleted. Do you want to proceed with the initialization?',
    m167: 'Refresh',
    m168: 'You use this option when overlay operation is abnormal.<br>The history will be deleted.',
    m90: 'Change the font installed on your computer.<br><font class="rdColor">= </font>Only PC',
    m102: 'Read before Setting',
    m103: 'When you type directly,<br>ACT > Plugins > ACTWebSocket > Click "Open Manager" > Tab "Preferences" > UNCHEKED "No Focus"',
    m101: '1. You only must be entered the font name. (EXCEPT font style)<br>2. If the font file is corrupted or font name is entered incorrectly, it will be applied by default.<br>3. This feature isn\'t supported in mobile environment.',
    m96: 'Time (00:00)',
    m97: 'General',
    m98: 'Korean',
    m99: 'Japanese',
    m104: 'English',
    m105: 'Deutsch',
    m176: 'Size',
    m177: '<span class="PrimaryText">Size<br><span class="SecondaryText"><font class="rdColor">= </font>8px ~ 32px</span></span>',
    m129: 'Color',
    m147: '<span class="PrimaryText">User<br><span class="SecondaryText"><font class="rdColor">= </font>YOU</span></span>',
    m148: '<span class="PrimaryText">Others<br><span class="SecondaryText"><font class="rdColor">= </font>Party Members</span></span>',
    m186: 'Bold lettring : User',
    m187: 'Applies bold formatting to the text of User in data table.',
    m188: 'Bold lettring : Others',
    m189: 'Applies bold formatting to the text of Others in data table.',
    m183: '<span class="PrimaryText">Height</span><br><span class="SecondaryText"><font class="rdColor">= </font>2 Increase or Decrease</span>',
    m100: 'Preview',
    m190: '<span class="PrimaryText">Background Color 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>Navigation Bar</span>',
    m172: '<span class="PrimaryText">Accent Color</span><br><span class="SecondaryText"><font class="rdColor">= </font>Time (00:00), Icon</span>',
    m199: '<span class="PrimaryText">Border Color</span><br><span class="SecondaryText"><font class="rdColor">= </font>Navigation Bar</span>',
    m191: '<span class="PrimaryText">Text Color 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>Target Name</span>',
    m192: '<span class="PrimaryText">Text Color 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>RDPS, RHPS</span>',
    m219: '<span class="PrimaryText">Background Color 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>Table Header</span>',
    m222: '<span class="PrimaryText">Text Color 3</span><br><span class="SecondaryText"><font class="rdColor">= </font>Table Header</span>',
    m221: 'Header Opacity',
    m194: 'Rounded Corner',
    m195: 'Rounded the left and right upper corners of the navigation bar.',
    m197: 'Draw Border',
    m198: 'An 1px border surrounds the navigation bar.',
    m181: 'Opacity',
    m193: 'Navigation Bar Opacity',
    m17: 'Graph Color',
    m119: 'Change the color of graph.',
    m88: 'Draw Division Lines',
    m89: 'Draw division lines between graphs.',
    m120: 'Fill Graph with Gradient',
    m121: 'Applies a gradient effect to the graph.',
    m122: 'Use Animated Transition Effect',
    m123: 'Shows graph smoothly when the DPS value or the HPS value is changed.',
    m15: 'Background Opacity',
    m18: 'Graph Opacity',
    m204: 'Effect',
    m217: 'Active the Raid Mode',
    m218: 'If the number of combatants exceeds nine people, the data table displays briefly.',
    m109: 'Narrow Cells',
    m111: 'Narrow Cells 1',
    m112: 'Cells with low variability of values.<br><font class="rdColor">= </font>Job, D%, Death etc',
    m113: 'Narrow Cells 2',
    m114: 'DPS, HPS ',
    m110: 'Wide Cells',
    m115: 'Wide Cells 1',
    m116: 'Cells with high variability of values.<br><font class="rdColor">= </font>Damage, Healed etc',
    m117: 'Wide Cells 2',
    m118: 'MaxHit, MaxHeal',
    m154: 'MopiMopi Overlay Skin',
    m155: 'Korea [Moogle] Haeru<br>GitHub <font class="rdColor">= </font>HAERUHAERU',
    m160: 'ACT Core Library : Chamsucript (js/core.js)',
    m161: 'Korea [Moogle] Laiglinne<Br>Elemental [Alexander] Lulala Lula<br>GitHub <font class="rdColor">= </font>laiglinne-ff',
    m156: 'Translation (Japanese)',
    m157: 'Korea [Moogle] Ikaruga',
    m271: 'Translation (Deutsch)',
    m272: 'Chaos [Phoenix] Shunittseru Tohka',
    m158: 'ACT WebSocket Overlay Plugin',
    m159: 'Korea [Carbuncle] CoolnyamCoolnyam<br>GitHub <font class="rdColor">= </font>ZCube',
    m205: 'Applies a User Color',
    m206: 'Applies the user\'s graph in a color you choose regardless of class or job.',
    m124: 'Tanker',
    m9: 'Color Code',
    m130: '<span class="PrimaryText">Paladin</span><br><span class="SecondaryText"><font class="rdColor">= </font>Gladiator</span>',
    m131: '<span class="PrimaryText">Warrior</span><br><span class="SecondaryText"><font class="rdColor">= </font>Marauder</span>',
    m132: '<span class="PrimaryText">Dark Knight</span>',
    m125: 'Healer',
    m133: '<span class="PrimaryText">White Mage</span><br><span class="SecondaryText"><font class="rdColor">= </font>Conjurer</span>',
    m134: '<span class="PrimaryText">Scholar</span>',
    m135: '<span class="PrimaryText">Astrologian</span>',
    m165: '<span class="PrimaryText">D.Shield</span><br><span class="SecondaryText"><font class="rdColor">= </font>Healer ACT</span>',
    m166: '<span class="PrimaryText">Overheal</span><br><span class="SecondaryText"><font class="rdColor">= </font>Healer ACT</span>',
    m126: 'Dealer',
    m136: '<span class="PrimaryText">Monk</span><br><span class="SecondaryText"><font class="rdColor">= </font>Pugilist</span>',
    m137: '<span class="PrimaryText">Dragoon</span><br><span class="SecondaryText"><font class="rdColor">= </font>Lancer</span>',
    m138: '<span class="PrimaryText">Ninja</span><br><span class="SecondaryText"><font class="rdColor">= </font>Rogue</span>',
    m231: '<span class="PrimaryText">Samurai</span>',
    m139: '<span class="PrimaryText">Black Mage</span><br><span class="SecondaryText"><font class="rdColor">= </font>Thaumaturge</span>',
    m140: '<span class="PrimaryText">Summoner</span><br><span class="SecondaryText"><font class="rdColor">= </font>Arcanist</span>',
    m232: '<span class="PrimaryText">Red Mage</span>',
    m141: '<span class="PrimaryText">Bard</span><br><span class="SecondaryText"><font class="rdColor">= </font>Archer</span>',
    m142: '<span class="PrimaryText">Machinist</span>',
    m127: 'Gathering / Crafting',
    m143: '<span class="PrimaryText">Gathering</span><br><span class="SecondaryText"><font class="rdColor">= </font>3 Kinds</span>',
    m144: '<span class="PrimaryText">Crafting</span><br><span class="SecondaryText"><font class="rdColor">= </font>8 Kinds</span>',
    m128: 'Other',
    m145: '<span class="PrimaryText">Limit Break</span>',
    m169: '<span class="PrimaryText">Pets Data</span><br><span class="SecondaryText"><font class="rdColor">= </font>Opacity 50%<br><font class="rdColor">= </font>on the User Graph</span>',
    m146: '<span class="PrimaryText">Chocobo</span><br><span class="SecondaryText"><font class="rdColor">= </font>Buddy</span>',
    m220: '<span class="PrimaryText">Background Color</span><br><span class="SecondaryText"><font class="rdColor">= </font>Graph Background</span>',
    m223: '<span class="PrimaryText">Division Lines Color</span><br><span class="SecondaryText"><font class="rdColor">= </font>Draw Division Lines \'ON\'</span>',
    m224: 'Division Lines Opacity',
    m32: 'Player\'s Info',
    m33: 'Combat',
    m34: 'Tanking',
    m35: 'Healing',
    m36: 'Etc',
    m37: 'The combatant\'s rank and name.',
    m214: 'The combatant\'s name.',
    m38: 'Player\'s class or job icon.',
    m39: 'The duration of the combatant.',
    m40: 'The damage total of the combatant divided by their personal duration.',
    m41: 'The duration of the encounter.',
    m42: 'The damage total of the combatant divided by the duration of the encounter.<br><font class="rdColor">= </font>This is more commonly used than P.DPS',
    m43: 'Average DPS for last 10 seconds.',
    m44: 'Average DPS for last 30 seconds.',
    m45: 'Average DPS for last 60 seconds.',
    m46: 'Average DPS for last 180 seconds.',
    m47: 'This value represents the percent share of all damage done by allies in this encounter.',
    m48: 'The amount of damage.',
    m49: 'The percentage of hits to swings.',
    m50: 'The number of attack attempts.<br><font class="rdColor">= </font>This includes any auto-attacks or abilities, also including resisted abilities that do no damage.',
    m51: 'The number of attack attempts that produced damage.',
    m52: 'The number of auto-attacks of CAs that produced a miss message.',
    m53: 'Any type of failed attack that was not a miss.<br><font class="rdColor">= </font>This includes resists, reflects, blocks, dodging, etc.',
    m54: 'The number of damaging attacks that were critical.',
    m55: 'The percentage of damaging attacks that were critical.',
    m56: 'The highest single damaging hit.',
    m57: 'The amount of damage this combatant received.',
    m58: 'The amount of healing this combatant received.',
    m59: 'The percentage of hits that were parried.',
    m60: 'The percentage of hits that were blocked.',
    m61: 'The healing total of the combatant divided by the duration of the encounter.',
    m62: 'The value represents the percent share of all healing done by allies in this encounter.',
    m63: 'The amount of healing.',
    m64: 'The amount of healing except for Overheal and D.Shield value.',
    m65: 'The amount of damage blocked by shield abilities of healer.<br><font class="rdColor">= </font>Galvanize effects, Nocturnal Field',
    m66: 'The amount of healing that made flood over 100% of health.',
    m67: 'The percentage of heals above target\'s Max HP.',
    m68: 'The number of heals from this combatant.',
    m69: 'The number of heals that were critical.',
    m70: 'The percentage of heals that were critical.',
    m71: 'The highest single healing amount.',
    m72: 'The number of times the combatant dispelled.<br><font class="rdColor">= </font>Esuna',
    m73: 'The amount of power this combatant drained from others.<br><font class="rdColor">= </font>ex. Mercy Stroke etc',
    m74: 'The amount of power this combatant replenished to others.<br><font class="rdColor">= </font>ex. Aetherflow etc',
    m75: 'The number of times this character was killed by another.',
    m76: 'The number of hits that were direct hit.',
    m77: 'The percentage of hits that were direct hits.',
    m78: 'The number of hits that were critical as well as direct hit.',
    m79: 'The percentage of hits that were direct hits as well as critical hits.',
};
mpDE = {																									
    m0: 'MopiMopi Overlay',																									
    m1: 'Warte auf Kampf.',																									
    m7: 'Historie<i class="material-icons left" style="color: rgba(255,255,255,0.5)">history</i>',																									
    m3: 'Namen ausblenden<i class="material-icons left" style="color: rgba(255,255,255,0.5)">visibility_off</i>',																									
    m2: 'Heiler ACT anzeigen<i class="material-icons left" style="color: rgba(255,255,255,0.5)">local_hospital</i>',																									
    m6: 'Vollbild Modus<i class="material-icons left" style="color: rgba(255,255,255,0.5)">fullscreen</i>',																									
    m5: 'Einstellungen<i class="material-icons left" style="color: rgba(255,255,255,0.5)">settings</i>',																									
    m10: 'Einstellungen',																									
    m20: 'Allgemein',																									
    m11: 'DPS Werte',																									
    m30: 'Wähle hier die Werte aus, die angezeigt werden sollen.',																									
    m12: 'Heiler Werte',																									
    m31: 'Wähle die Werte aus, die angezeigt werden wenn \'Heiler ACT anzeigen\' aktiviert ist.',																									
    m21: 'Anzeigeeinstellungen',																									
    m80: 'Charakter und Begleiter zusammenfassen',																									
    m81: 'Fasse die Werte des Charakters und dessen Begleiter zusammen<br><font class="rdColor">= </font>SMN, MCH, SCH',																									
    m170: 'Kombinierte Graphen',																									
    m171: 'Zeigt prozentual den Schaden oder die Heilung des Begleiters im Graph des Charakters an<br><font class="rdColor">Vorraussetzung = </font>  \'Charakter und Begleiter zusammenfassen\' aktiviert',																									
    m82: 'Datentyp der Zahlen',																									
    m83: '<font class="rdColor">OFF </font>Integer<font class="rdColor">　　ON </font>Dezimal',																									
    m84: 'Tausender Trennzeichen',																									
    m85: '<font class="rdColor">OFF </font>1234<font class="rdColor">　　ON </font>1,234',																									
    m207: 'Anzeigetyp des Namens',																									
    m208: 'Voller Name',																									
    m209: 'Nachname abgekürzt',																									
    m210: 'Vorname abgekürzt',																									
    m211: 'Initialien',																									
    m212: 'Sortierung',																									
    m213: '<font class="rdColor">OFF </font>Nach DPS sortiert<font class="rdColor">　　ON </font>1. Platz = DU',																									
    m225: 'Globale Einstellungen',																									
    m226: 'Passe die Formatierung der Charakternamen und die Zahlenschreibweise an.',																									
    m227: 'Nutze Europäische Notation',																									
    m228: 'Tausche Punkt(.) gegen Komma(,) bei Zahlen (und umgekehrt).',																									
    m229: 'Abgekürzte Fähigkeitsnamen',																									
    m230: '<font class="rdColor">OFF </font>Midare Setsugekka<font class="rdColor">　　ON </font>Midare',																									
    m233: 'Automatisches ausblenden der Daten',																									
    m234: 'Blendt automaitsch nach einer Verzögerung die Daten aus, sobald der Kampf vorbei ist.',																									
    m235: 'Weitere Einstellungen',																									
    m236: 'Passe weitere Einstellungen an.<br><font class="rdColor">= </font>Overlay, Tabelle, usw.',																									
    m237: 'Pfeil zur Größenveränderung des Fensters',																									
    m238: '<font class="rdColor">OFF </font>Ausblenden<font class="rdColor">　　ON </font>Anzeigen',																									
    m239: 'Tabelle - Data Table',																									
    m240: 'Kurzhinweise im Menü',																									
    m241: 'Toast-Benachrichtigungen',																									
    m242: '<span class="PrimaryText">Latenz</span><br><span class="SecondaryText"><font class="rdColor">= </font>Einheit \'Minute\'</span>',																									
    m243: 'Sicherung',																									
    m244: 'Erstelle Sicherungen deiner Einstellungen und teile sie mit anderen oder stell die Einstellungen (von anderen) wieder her.',																									
    m245: '<span>Zeit der letzten Sicherung <font id="backupDate" class="rdColor"></font></span>',																									
    m246: 'Wiederherstellen', 																									
    m247: 'Stelle die Einstellungen der Benutzeroberfläche wieder her.',																									
    m248: 'Meine Daten',																									
    m249: 'Exportiere die Anzeigeeinstellungen', 																									
    m250: 'Importiere die Anzeigeeinstellungen', 																									
    m251: 'Kopiere die unteren Werte (Strg+C). Manche Daten sind nicht enthalten.', 																									
    m252: 'Füge kopierte Werte unten ein (Strg+V) und drücke die Eingabetaste.',																									
    m253: 'Sichern und Wiederherstellen',																									
    m254: 'Kein Sicherung vorhanden. Bitte klicke um eine zu erstellen.',																									
    m255: 'Möchtest du die Einstellungen wirklich wiederherstellen?',																									
    m256: 'Index',																									
    m257: 'Reihenfolge der Daten',																									
    m258: 'Passe die Reihenfolge der Spalten in der Datentabelle an.',																									
    m259: 'Eigener Charaktername',																									
    m260: '<font class="rdColor">OFF </font>DU<font class="rdColor">　　ON </font> (z.B.) Shunittseru Tohka',																									
    m261: 'Einstellungen der Abgekürzten Fähigkeitsnamen.',																									
    m262: 'Hier kannst du Abkürzungen der Fähigkeiten neu erstellen oder löschen.',																									
    m263: '',																									
    m264: 'Register',																									
    m265: 'Fähigkeitsname (Achte auf Leerzeichen!)',																									
    m266: 'Abkürzung',																									
    m267: 'Liste der aktiven Abkürzungen',																									
    m268: 'Hinzufügen',		
    m269: 'Textausrichtung',
    m270: '<font class="rdColor">OFF </font>Zentriert<font class="rdColor">　　ON </font>Linksbündig',																						
    m22: 'Anzeige',																									
    m13: 'Sprache',																									
    m14: 'Schrift',																									
    m184: 'Ändere die Einstellungen der Schrift.<br><font class="rdColor">= </font>Schriftart, Schriftgröße, Schriftfarbe, Stil',																									
    m19: 'Navigationsleiste',																									
    m86: 'Entwerfe ein Design, welches deinen Bedürfnissen gerecht wird.',																									
    m23: 'Diagramm',																									
    m87: 'Ändere die Einstellungen des Diagrammes.<br><font class="rdColor">= </font>Farbe, Effekte, Deckkraft',																									
    m16: 'Zellenbreite',																									
    m91: 'Passe die Weite der Zellen (gruppiert) an.',																									
    m24: 'Version und Entwickler Informationen',																									
    m150: 'Version',																									
    m152: 'Kontaktiere uns',																									
    m153: 'ffxivHAERU@gmail.com',																									
    m200: 'Über die Entwickler',																									
    m201: 'Overlay, Plugin, Übersetzung',																									
    m25: 'Zurücksetzen',																									
    m26: 'Management Tools',																									
    m162: 'Nutze diese Option um alle Werkseinstellungen wiederherzustellen.',																									
    m163: 'Alle Einstellungen werden zurück gesetzt. Deine persönlichen Einstellungen gehen unwiderruflich verloren! Möchtest du fortfahren?',																									
    m167: 'Auffrischen',																									
    m168: 'Nutze diese Option, falls das Overlay nicht richtig funktioniert.<br>Die Historie wird gelöscht.',																									
    m90: 'Ändere die Schriftart (muss installiert sein auf dem Computer).<br><font class="rdColor">= </font>Ausschließlich auf diesem PC',																									
    m102: 'Erst alles genau durchlesen, dann Einstellungen vornehmen!',																									
    m103: 'Wenn du direkt schreiben möchtest, gehe wie folgt vor:,<br>ACT > Plugins > ACTWebSocket > Klicke auf "Open Manager" > Tab "Preferences" > DEAKTIVIERE "No Focus"',																									
    m101: '1. Nur den Schriftart-Namen eintragen.(AUSNAHME: Schriftstil)<br>2. Falls die Datei der Schriftart beschädigt oder der Name falsch geschrieben ist, wird die Standard-Schriftart angewendet.<br>3. Dieses Feature wird nicht in der mobilen Umgebung unterstützt.',																									
    m96: 'Time (00:00)',																									
    m97: 'Allgemeines',																									
    m98: 'Koreanisch',																									
    m99: 'Japanisch',																									
    m104: 'Englisch',
    m105: 'Deutsch',																									
    m176: 'Größe',																									
    m177: '<span class="PrimaryText">Size<br><span class="SecondaryText"><font class="rdColor">= </font>8px ~ 32px</span></span>',																									
    m129: 'Farbe',																									
    m147: '<span class="PrimaryText">Nutzer<br><span class="SecondaryText"><font class="rdColor">= </font>DU</span></span>',																									
    m148: '<span class="PrimaryText">Andere<br><span class="SecondaryText"><font class="rdColor">= </font>Gruppen Mitglieder</span></span>',																									
    m186: 'Fette Buchstaben: Nutzer',																									
    m187: 'Formatiert den Text des Nutzers in der Tabelle fett.',																									
    m188: 'Fette Buchstaben: Andere',																									
    m189: 'Formatiert den Text der Anderen in der Tabelle fett.',																									
    m183: '<span class="PrimaryText">Höhe</span><br><span class="SecondaryText"><font class="rdColor">= </font>In zweier Schritten einstellbar</span>',																									
    m100: 'Vorschau',																									
    m190: '<span class="PrimaryText">Hintergrund Farbe 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>Navigationsleiste *</span>',																									
    m172: '<span class="PrimaryText">Farbakzent</span><br><span class="SecondaryText"><font class="rdColor">= </font>Zeit (00:00), Symbole</span>',																									
    m199: '<span class="PrimaryText">Randfarbe</span><br><span class="SecondaryText"><font class="rdColor">= </font>Navigationsleiste *</span>',																									
    m191: '<span class="PrimaryText">Textfarbe 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>Name des Ziels</span>',																									
    m192: '<span class="PrimaryText">Textfarbe 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>RDPS, RHPS</span>',																									
    m219: '<span class="PrimaryText">Hintergrund Farbe 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>Tabellenkopf *</span>',																									
    m222: '<span class="PrimaryText">Textfarbe 3</span><br><span class="SecondaryText"><font class="rdColor">= </font>Tabellenkopf *</span>',																									
    m221: 'Deckkraft Header',																									
    m194: 'Abgerundete Ecken',																									
    m195: 'Runde die obere linke sowie rechte Ecke der Navigationsleiste ab.',																									
    m197: 'Rand anzeigen',																									
    m198: 'Zeige einen 1px großen Rand an, welcher die Navigationsleiste umgibt.',																									
    m181: 'Deckkraft',																									
    m193: 'Deckkraft Navigationsleiste',																									
    m17: 'Farbe der Graphen',																									
    m119: 'Ändere die Farben der Graphen.',																									
    m88: 'Trennlinien anzeigen',																									
    m89: 'Zeige Trennlinien zwischen den Graphen an.',																									
    m120: 'Gradient-Effekt',																									
    m121: 'Abnehmende Deckkraft der Farbe des Graphen',																									
    m122: 'Weicher, Animierter Übergang',																									
    m123: 'Graph wird bei Update des DPS/HPS weich animiert.',																									
    m15: 'Deckkraft Hintergrund',																									
    m18: 'Deckkraft Graph',																									
    m204: 'Effekt',																									
    m217: 'Aktiviere den Raid Modus',																									
    m218: 'Automatische Anpassung der Graphen, falls die Anzahl der Kämpfer > 9 beträgt.',																									
    m109: 'Schmale Spalten',																									
    m111: 'Schmale Spalten 1',																									
    m112: 'Spalten mit geringer Breite und wenig wechselnden Werten<br><font class="rdColor">= </font>Job, D%, Tote, usw.',																									
    m113: 'Schmale Spalten 2',																									
    m114: '<font class="rdColor">= </font>DPS, HPS',																									
    m110: 'Breite Spalten',																									
    m115: 'Breite Spalten 1',																									
    m116: 'Spalten mit erweiterter Breite und stark wechselnden Werten.<br><font class="rdColor">= </font>Schaden, Heilung, usw.',																									
    m117: 'Breite Spalten 2',																									
    m118: 'MaxHit, MaxHeal',																									
    m154: 'MopiMopi Overlay Skin',																									
    m155: 'Korea [Moogle] Haeru<br>GitHub <font class="rdColor">= </font>HAERUHAERU',																									
    m160: 'ACT Core Bibliothek : Chamsucript (js/core.js)',																									
    m161: 'Korea [Moogle] Laiglinne<Br>Elemental [Alexander] Lulala Lula<br>GitHub <font class="rdColor">= </font>laiglinne-ff',																									
    m156: 'Übersetzung (Japanisch)',																									
    m157: 'Korea [Moogle] Ikaruga',	    
    m271: 'Übersetzung (Deutsch)',
    m272: 'Chaos [Phoenix] Shunittseru Tohka',																								
    m158: 'ACT WebSocket Overlay Plugin',																									
    m159: 'Korea [Carbuncle] CoolnyamCoolnyam<br>GitHub <font class="rdColor">= </font>ZCube',																									
    m205: 'Eigene Farbe für eigenen Charakter',																									
    m206: 'Nutze eine selbst ausgewählte Farbe für den eigenen Charakter. Überschreibt Klassen/Job Farben',																									
    m124: 'Verteidiger',																									
    m9: 'Farb Code',																									
    m130: '<span class="PrimaryText">Paladin</span><br><span class="SecondaryText"><font class="rdColor">= </font>Gladiator</span>',																									
    m131: '<span class="PrimaryText">Krieger</span><br><span class="SecondaryText"><font class="rdColor">= </font>Marodeur</span>',																									
    m132: '<span class="PrimaryText">Dunkelritter</span>',																									
    m125: 'Heiler',																									
    m133: '<span class="PrimaryText">Weißmagier</span><br><span class="SecondaryText"><font class="rdColor">= </font>Druide</span>',																									
    m134: '<span class="PrimaryText">Gelehrter</span>',																									
    m135: '<span class="PrimaryText">Astrologe</span>',																									
    m165: '<span class="PrimaryText">Schilde</span><br><span class="SecondaryText"><font class="rdColor">= </font>Healer ACT *</span>',																									
    m166: '<span class="PrimaryText">Overheal</span><br><span class="SecondaryText"><font class="rdColor">= </font>Healer ACT *</span>',																									
    m126: 'Angreifer',																									
    m136: '<span class="PrimaryText">Mönch</span><br><span class="SecondaryText"><font class="rdColor">= </font>Faustkämpfer</span>',																									
    m137: '<span class="PrimaryText">Dragoon</span><br><span class="SecondaryText"><font class="rdColor">= </font>Pikinier</span>',																									
    m138: '<span class="PrimaryText">Ninja</span><br><span class="SecondaryText"><font class="rdColor">= </font>Schurke</span>',																									
    m231: '<span class="PrimaryText">Samurai</span>',																									
    m139: '<span class="PrimaryText">Schwarzmagier</span><br><span class="SecondaryText"><font class="rdColor">= </font>Thaumaturg</span>',																									
    m140: '<span class="PrimaryText">Beschwörer</span><br><span class="SecondaryText"><font class="rdColor">= </font>Hermetiker</span>',																									
    m232: '<span class="PrimaryText">Rotmagier</span>',																									
    m141: '<span class="PrimaryText">Barde</span><br><span class="SecondaryText"><font class="rdColor">= </font>Waldläufer</span>',																									
    m142: '<span class="PrimaryText">Maschinist</span>',																									
    m127: 'Sammler und Handwerker',																									
    m143: '<span class="PrimaryText">Sammler</span><br><span class="SecondaryText"><font class="rdColor">= </font>MIN, FIS, GÄR</span>',																									
    m144: '<span class="PrimaryText">Handwerker</span><br><span class="SecondaryText"><font class="rdColor">= </font>8 Arten</span>',																									
    m128: 'Andere',																									
    m145: '<span class="PrimaryText">Limitrausch</span>',																									
    m169: '<span class="PrimaryText">Begleiter Daten</span><br><span class="SecondaryText"><font class="rdColor">= </font>Deckkraft 50%<br><font class="rdColor">= </font>auf dem Graph des Charakters *</span>',																									
    m146: '<span class="PrimaryText">Chocobo</span><br><span class="SecondaryText"><font class="rdColor">= </font>Buddy</span>',																									
    m220: '<span class="PrimaryText">Hintergrundfarbe</span><br><span class="SecondaryText"><font class="rdColor">= </font>Graph Background *</span>',																									
    m223: '<span class="PrimaryText">Trennlinienfarbe</span><br><span class="SecondaryText"><font class="rdColor">= </font>Falls \'Trennlinien anzeigen\' aktiviert</span>',																									
    m224: 'Deckkraft Trennlinien',																									
    m32: 'Charakter Informationen',																									
    m33: 'Kampf Informationen',																									
    m34: 'Eingehender Schaden',																									
    m35: 'Heilung',																									
    m36: 'Anderes',																									
    m37: 'Rank und Name des Kämpfers',																									
    m214: 'Kämpfername.',																									
    m38: 'Klassen/Job-Icon des Kämpfers',																									
    m39: 'Kampfzeit des Charakters',																									
    m40: 'Gesamtschaden der Person dividiert durch die persönliche Kampfzeit.',																									
    m41: 'Die Kampfzeit.',																									
    m42: 'Gesamtschaden dividiert durch die Kampfzeit.<br><font class="rdColor">= </font>Diese Option ist weiter verbreitet als P.DPS',																									
    m43: 'Durchschnittlicher DPS der letzten 10 Sekunden.',																									
    m44: 'Durchschnittlicher DPS der letzten 30 Sekunden.',																									
    m45: 'Durchschnittlicher DPS der letzten 60 Sekunden.',																									
    m46: 'Durchschnittlicher DPS der letzten 180 Sekunden.',																									
    m47: 'Prozentualer Anteil am Gesamtschadens der Gruppe.',																									
    m48: 'Summe des verursachten Schadens.',																									
    m49: 'Prozentuale Treffergenauigkeit.',																									
    m50: 'Ausgeführte Aktionen.<br><font class="rdColor">= </font>Umfasst jede Auto-Attacke und Fähigkeit.',																									
    m51: 'Ausgeführte Aktionen, welche Schaden verursacht haben.',																									
    m52: 'Anzahl der Auto-Attacken oder Fähigkeiten welche nicht getroffen haben.',																									
    m53: 'Anzahl der Attacken, die keinen Schaden verursacht haben, aber kein Miss waren.<br><font class="rdColor">= </font>Umfasst: Widerstände, Reflektionen, Ausgeweichen, blocken, usw.',																									
    m54: 'Anzahl der kritischen Treffer.',																									
    m55: 'Prozentualer Anteil der kritischen Treffer.',																									
    m56: 'Höchster verursachter Schaden durch einen Angriff.',																									
    m57: 'Summe des erhaltenen Schadens.',																									
    m58: 'Summe der erhaltenen Heilung.',																									
    m59: 'Prozentualer Anteil an parrierten Treffern.',																									
    m60: 'Prozentualer Anteil an geblockten Treffern.',																									
    m61: 'Summe der verursachen Heilung dividiert durch die Kampfzeit.',																									
    m62: 'Prozentualer Anteil an der gesamten Heilung der Gruppe.',																									
    m63: 'Summe der verursachten Heilung.',																									
    m64: 'Summe der verursachten Heilung, Overheal und Schilde ausgenommen.',																									
    m65: 'Summe des Schadens, welcher durch Schilde der Healer absorbiert wurde.<br><font class="rdColor">= </font>Adloquium, Nocturnales Feld, ...',																									
    m66: 'Summe der Heilung, welche über 100% Gesundheit verursacht wurde.',																									
    m67: 'Prozentualer Anteil der Heilung, welche über 100% Gesundheit verursacht wurde.',																									
    m68: 'Anzahl der verursachen Heilungen (Umfasst auch Heilung von jedem Tick von HoTs wie Regena).',																									
    m69: 'Anzahl der Heilung, welche kritisch getroffen hat.',																									
    m70: 'Prozentualer Anteil der Heilung, welche kritisch getroffen hat.',																									
    m71: 'Größte verursachte Heilung.',																									
    m72: 'Anzahl der Zauber, welche negative Statuseffekte entfernt haben.<br><font class="rdColor">= </font>Medica, Päan des Hüters',																									
    m73: 'Summe der Lebenspunkte, die durch Kampffähigkeiten regeneriert wurden.<br><font class="rdColor">= </font>Blutbad, usw.',																									
    m74: 'Summe der Mana, die durch Fähigkeiten regneriert wurde.<br><font class="rdColor">= </font>Ätherfuss, Assise, usw.',																									
    m75: 'Anzahl der Tode.',																									
    m76: 'Anzahl der Treffer, die direkt getroffen haben.',																									
    m77: 'Prozentualer Anteil der Treffer, die direkt getroffen haben.',																									
    m78: 'Anzahl der Treffer, die direct und kritisch getroffen haben.',																									
    m79: 'Prozentualer Anteil der Treffer,  die direct und kritisch getroffen haben.',																									
    };																									
    
